name: Build Windows exe 
on: workflow_dispatch
  
jobs:

  build-windows-exe:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.7'
      
      - name: Install InnoSetup if missing
        run: |
          if (-not (Get-Command "innosetup" -ErrorAction SilentlyContinue)) {
            choco install innosetup -y
          } else {
            Write-Output "InnoSetup already installed."
          }

      - name: Update lang data
        working-directory: "${{ github.workspace }}"
        run: dart localization/generator.dart

      - name: Set update check flag to true
        working-directory: "${{ github.workspace }}/lib/utils"
        run: echo "const updateCheckFlag = true;" > update_check_flag_file.dart
        
      - name: Build windows exe package
        working-directory: "${{ github.workspace }}"
        run: |
          flutter clean
          dart pub global activate flutter_distributor
          flutter_distributor package --platform windows --targets exe

      - name: Find first .exe file
        id: find_exe
        run: |
          $lastSubDir = Get-ChildItem -Path "${{ github.workspace }}/dist" -Directory | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          $exeFile = Get-ChildItem -Path "$($lastSubDir.FullName)/*.exe" | Select-Object -First 1
          if ($exeFile) {
              echo "Found .exe file: $($exeFile.FullName)"
              echo "::set-output name=exe_path::$($exeFile.FullName)"
          } else {
              Write-Error "No .exe files found in the dist directory."
              exit 1
          }

      - name: Upload Windows exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony music windows exe
          path: "${{ github.workspace }}/dist/**/*.exe"
